name: Commit messages.

on:
  pull_request:
    branches: [main]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    container:
      image: alpine:3
    steps:
      - name: Install Git
        run: |
          apk add --no-cache git

      - name: Configure Git
        run: |
          git config --global --add safe.directory /__w/ResourceSystemManager/ResourceSystemManager

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check commit messages
        run: |
          commit_hashes=$(git rev-list 13a23017f12a1d46b586d1950723df92ace8b04e..849e478db01cb3eb9d08ac6a1f2106792e7bf2ea)

          for hash in $commit_hashes; do
            subject=$(git log -1 --format=%s "$hash")
            if ! echo "$subject" | grep -Eq "^(RSM-[0-9]+|TRIVIAL|DOC|WORKFLOW): .+"; then
              echo "Invalid commit message format in commit $hash:"
              echo "  $subject"
              echo "Commit messages must match pattern: (RSM-\\d+)|(TRIVIAL)|(DOC)|(WORKFLOW): ..."
              exit 1
              fi
              done
